//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnglishTeacher.Models
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract]
    public partial class Lernt_words
    {
        public string id_lernt_word { get; set; }
        public string id_user { get; set; }
        public int id_theme { get; set; }
        public string id_word { get; set; }
    
        public virtual Theme Theme { get; set; }
        public virtual Word Word { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
