//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnglishTeacher.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Setting
    {
        public string id_setting { get; set; }
        public string id_user { get; set; }
        public bool turn_on { get; set; }
        public double frequency { get; set; }
        public int font_size { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
