//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnglishTeacher.Models
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract]
    [KnownType(typeof(Theme))]
    [KnownType(typeof(ICollection<Lernt_words>))]
    public partial class Word
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Word()
        {
          //  this.Lernt_words = new HashSet<Lernt_words>();
        }

        [DataMember]
        public string id_word { get; set; }
        [DataMember]
        public int id_theme { get; set; }
        [DataMember]
        public string word1 { get; set; }
        [DataMember]
        public string transcription { get; set; }
        [DataMember]
        public string translate { get; set; }
    
       [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
       [DataMember]
       public virtual ICollection<Lernt_words> Lernt_words { get; set; }
        
       public virtual Theme Theme { get; set; }
    }
}
